name: CI

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      acr_registry: ${{secrets.AZURE_ACR_REGISTRY}}
      acr_login: ${{secrets.AZURE_ACR_LOGIN_SERVER}}
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: echo Running build!
    - name: Build web app
      run: |
        npm install
        npm run build
        docker-compose -f ./docker-compose-stg.yml build
    - name: Send to Azure
      run: |
        az acr login --name $acr_registry
        docker tag prj2testimage $acr_login/prj2testimage:v1
        docker push $acr_login/prj2testimage:v1
        az acr repository list --name $acr_registry --output table

