name: CI

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: echo Running build!
    - name: Build web app
      run: |
        npm install
        npm run build
        docker-compose -f ./docker-compose-stg.yml build
